### ISSUE TITLE
Is this where development of pywhdfs now takes place? Would you like help?

### ISSUE THREAD

**Issue by moreati** [yassineazzouz/pywhdfs#2]
Hi Yassine, I see that this repository has more recent commits than https://bitbucket.org/suty/pyhdfs. Have you moved the project here?

I've picked up your Ansible `hdfsfile` pull request, and I'd like to help with this library too, if you're interested.

Best wishes, Alex

**Comment by yassineazzouz** [comment]
Hi Alex,

Yes I no longer use the one in bitbucket, I should probably just close that project. This is the active repository, well not sure if I should call it active, I did not do much in it for sometime now. Yes please, any help is appreciated :) feel free to PR.

Thanks,

**Comment by moreati** [comment]
WIll do, thanks for responding
