### ISSUE TITLE
Can't install due to missing python-krbV

### ISSUE THREAD

**Issue by youssefaz94** [yassineazzouz/pywhdfs#4]
`Searching for python-krbV
Reading https://pypi.org/simple/python-krbV/
Couldn't find index page for 'python-krbV' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for python-krbV
error: Could not find suitable distribution for Requirement.parse('python-krbV')`

it looks like recently the python-krbV PyPI package was removed.
[https://pypi.org/project/python-krbV/](https://pypi.org/project/python-krbV/)

RedHat replaced the usage of other Python-kerberos packages with GSSAPI [https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/pdf/considerations_in_adopting_rhel_8/Red_Hat_Enterprise_Linux-8-Considerations_in_adopting_RHEL_8-en-US.pdf](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/pdf/considerations_in_adopting_rhel_8/Red_Hat_Enterprise_Linux-8-Considerations_in_adopting_RHEL_8-en-US.pdf) - see chapter "17.4.2. Selected Python Kerberos packages have been replaced".

**Comment by yassineazzouz** [comment]
resolved in 1.0.9
